apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: control-tower
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: control-tower
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
